### ISSUE TITLE
Error horizontal-scroller-left.tiff

### ISSUE THREAD

**Issue by no-e-in** [nicolas-p/skov#13]
In windows 7 with factor-windows-x86-64-0.98, there is error:
[horizontal-scroller-left.tiff](https://ibb.co/YLbCf1T)

**Comment by mrjbq7** [comment]
That URL doesn't seem to work?

**Comment by mrjbq7** [comment]
Do you have any traceback?  I assume it's coming from ``theme-image``.  I just checked and that file should be available in the release binary.  Is it missing from your installation?

**Comment by no-e-in** [comment]
It is in factor\basis\ui\theme\images. It is a problem with Skov, not with Factor that is working properly.
