### ISSUE TITLE
Hidden or overlapping elements.

### ISSUE THREAD

**Issue by kustomzone** [nicolas-p/skov#6]
When following the tutorial (eg. distance between two points) and creating 'point A' with destructor, then 'point B' with destructor, and start to wire them up, 'point B' suddenly jumps on top of (obscures) 'point A'. 

Is there a way to re-position them so that they are not completely overlapping each other?

(so far i'm only able to build the distance object if i wire them at different steps to have enough mismatching overlap to be able to continue the construction)

**Comment by nicolas-p** [comment]
I am aware about this issue.

The graph layout algorithm has been by far the hardest thing to develop in this project. I tried many different (bad) ideas before converging towards the current algorithm that works satisfyingly in 95% of cases. But I know it's still not perfect.

So currently, if you end up in a situation where nodes overlap, the solution is to go back (disconnect nodes by placing the cursor on a connector and pressing X) and try to wire them up in a different order.

I am not in favor of allowing manual re-positionning. If the automatic layout algorithm doesn't work as expected, then the right thing to do is to improve the algorithm, not to fall back on the easy solution of manual layout.

**Comment by kustomzone** [comment]
Sure, i understand the goal of keeping the layout in an automatic functioning mode.

Perhaps an [alt] key or toggle switch (whichever doesn't interfere with keyboard shortcuts is fine) that slides a slight horizontal gap between the overlapped objects as a temporary state (but only when it's pressed or toggled) and snaps back to automatic positions when released, just so we can make another connection which will re-orient the layout, thus saving us from disconnecting or removing our construction.

**Comment by nicolas-p** [comment]
I've thought a bit about it and I think the right thing to do is to build a safety mechanism at the end of the graph layout algorithm so that if it generates a bad layout with overlapping nodes, the problematic nodes will be moved so that they don't overlap. The layout will still look bad, but at least it will be usable.

**Comment by nicolas-p** [comment]
This issue has become irrelevant in New Skov (see #12).
