### ISSUE TITLE
Cannot export code

### ISSUE THREAD

**Issue by jkleiser** [nicolas-p/skov#7]
The answer to the last "FAQ" question "How can I share ...?", says "If you press Ctrl-D, Skov will export ...". I have tried both Ctrl-D and Cmd-D on my Mac, but nothing gets exported into the work folder. I hope this can be fixed, as it is quite critical.

**Comment by nicolas-p** [comment]
The mistake on the website was fixed last night, it's Ctrl+S.
(But I had forgotten to fix the French version.)

I wanted it to be Cmd+S on Macs but it has to be Ctrl+S because of a design choice that the developers of Factor made.

**Comment by mrjbq7** [comment]
You can make it Cmd-S by looking up `os` and doing different key accelerators on different platforms.

**Comment by jkleiser** [comment]
Thanks.
